{% set name = "python-logstash-async" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 000fe0cff7775c99ecc99d2c1f07ef5ba6313a4e3d184e21802d2ca78d4f0a97

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - limits
    - pylogbeat
    - requests
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - logstash_async
    - logstash_async.worker

about:
  home: "https://github.com/eht16/python-logstash-async"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Asynchronous Python logging handler for Logstash."
  doc_url: https://python-logstash-async.readthedocs.io/en/latest/
  dev_url: https://github.com/eht16/python-logstash-async

extra:
  recipe-maintainers:
    - tiefling-cat
